#pragma once

#define VIAL_KEYBOARD_UID {0x01, 0x8F, 0xC6, 0xFF, 0xB4, 0x6A, 0x24, 0xF7}
#define VIAL_UNLOCK_COMBO_ROWS {1, 2}
#define VIAL_UNLOCK_COMBO_COLS {0, 0}

/* Use I2C or Serial, not both */
#define USE_SERIAL
// #define USE_I2C

/* Select hand configuration */
// #define MASTER_LEFT
// #define MASTER_RIGHT
#define EE_HANDS
// #define SPLIT_USB_DETECT
// [Bug] SPLIT_USB_DETECT prevents keyboard detection on cold boot

#define PREVENT_STUCK_MODIFIERS

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #define RGBLIGHT_EFFECT_SNAKE
// #define RGBLIGHT_EFFECT_KNIGHT
// #define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE

/*
#define RGBLIGHT_LAYERS
#define RGBLIGHT_SPLIT
#define RGBLED_SPLIT { 10, 10 }
*/
#undef RGBLED_NUM
#define RGBLED_NUM 10

#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
